# pulled from https://github.com/satai/todotxt-fish-goodies/blob/master/todotxt.fish

alias t "todo.sh"
alias ta "todo.sh add"
alias tl "todo.sh ls"
alias tls "todo.sh ls"
alias trm "todo.sh rm"
alias tdo "todo.sh do"

alias vimt "vim ~/.todo/todo.txt"
alias vimp "vim ~/.todo/Projects.txt"

complete -c t -s @ --description "Hide context names in list output"
complete -c t -s + --description "Hide project names in list output"
complete -c t -o @@ --description "Show context names in list output"
complete -c t -o ++ --description "Show project names in list output"
complete -c t -s c --description "Color mode"
complete -c t -s D --description "Alternate configuration file"
complete -c t -s f --description "Force actions without confirmation"
complete -c t -s p --description "Plain mode, disable colors"
complete -c t -s P --description "Disable priority labels"
complete -c t -s a --description "Auto archive done tasks"
complete -c t -s n --description "Preserve line numbers"
complete -c t -s N --description "Don't preserve line numbers"
complete -c t -s t --description "Prepend current date when adding task"
complete -c t -s T --description "Don't prepend current date when adding task"
complete -c t -s v --description "Verbose mode"
complete -c t -s vv --description "Extra verbose mode"
complete -c t -s x --description "Disable TODOTXT_FINAL_FILTER"

complete -c t -a add -r --description "Adds task"
complete -c t -a a -r --description "Adds task"
complete -c t -a addm -r --description "Adds multiple tasks"
complete -c t -a addto -r --description "Adds line to a file in todo.tx directory"
complete -c t -a append -r --description "Appends text to a task"
complete -c t -a app -r --description "Appends text to a task"
complete -c t -a archive -r --description "Moves all done tasks done.txt"
complete -c t -a deduplicate -r --description "Removes duplicate tasks"
complete -c t -a del -r --description "Deletes a task"
complete -c t -a rm -r --description "Deletes a task"
complete -c t -a depri -r --description "Removes priority of a task"
complete -c t -a dp -r --description "Removes priority of a task"
complete -c t -a do -r --description "Markes a task as done"
complete -c t -a help -r --description "Prints help"
complete -c t -a ls -r --description "Lists tasks"
complete -c t -a list -r --description "Lists tasks"
complete -c t -a lsa -r --description "Lists tasks"
complete -c t -a listall -r --description "Lists tasks including done tasks"
complete -c t -a listaddons -r --description "Lists addons"
complete -c t -a listcon -r --description "Lists contexts"
complete -c t -a lsc -r --description "Lists contexts"
complete -c t -a listsproj -r --description "Lists projects"
complete -c t -a lsprj -r --description "Lists projects"
complete -c t -a listpri -r --description "Lists tasks with priority"
complete -c t -a lsp -r --description "Lists tasks with priority"
complete -c t -a move -r --description "Moves task between files"
complete -c t -a prepend -r --description "Prepends text to a task"
complete -c t -a prep -r --description "Prepends text to a task"
complete -c t -a pri -r --description "Sets priority to a task"
complete -c t -a p -r --description "Sets priority to a task"
complete -c t -a replace -r --description "Replaces task with new one"
complete -c t -a report -r --description "Reports to report.txt"

complete -c t -r -f
complete -c t --description "Context" -a "(todo.sh listcon)"
complete -c t --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
complete -c t --description "Project" -a "(todo.sh listproj)"
complete -c t --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"

complete -c tls -r -f
complete -c tls --description "Context" -a "(todo.sh listcon)"
complete -c tls --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
complete -c tls --description "Project" -a "(todo.sh listproj)"
complete -c tls --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"

complete -c tl -r -f
complete -c tl --description "Context" -a "(todo.sh listcon)"
complete -c tl --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
complete -c tl --description "Project" -a "(todo.sh listproj)"
complete -c tl --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"

complete -c ta -r -f
complete -c ta --description "Context" -a "(todo.sh listcon)"
complete -c ta --description "Context" -a "(cat ~/.todo/Contexts.txt | cut -f 1 -d ' ')"
complete -c ta --description "Project" -a "(todo.sh listproj)"
complete -c ta --description "Project" -a "(cat ~/.todo/Projects.txt | cut -f 1 -d ' ')"

