#!/bin/bash
#
# author: orefalo
# http://stackoverflow.com/questions/8730514/chaining-git-hooks

hookname=`basename $0`


FILE=`mktemp tmp.XXXXXXX`
trap 'rm -f $FILE' EXIT
cat - > $FILE

for hook in $GIT_DIR/hooks/$hookname.*
do
    if test -x "$hook"; then
#       echo $hook
        cat $FILE | $hook "$@"
        status=$?

        if test $status -ne 0; then
            echo Hook $hook failed with error code $status
            exit $status
        fi
    fi
done
